export const ADD_RECIPE = 'ADD_RECIPE';
export const SEARCH_RECIPES = 'SEARCH_RECIPES';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';

export const FETCH_RECIPES_BEGIN   = 'FETCH_RECIPES_BEGIN';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';

export const FETCH_RECIPE_BEGIN   = 'FETCH_RECIPE_BEGIN';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
export const FETCH_RECIPE_FAILURE = 'FETCH_RECIPE_FAILURE';
